"use server";

import nodemailer from "nodemailer";

interface ContactData {
	name: string;
	email: string;
	phone: string;
	projectType: string;
	message: string;
}

export async function sendContactEmail(formData: ContactData) {
	// Configure SMTP Transporter
	// These values will be read from environment variables (.env.local)
	const transporter = nodemailer.createTransport({
		host: process.env.SMTP_HOST || "smtp.gmail.com",
		port: parseInt(process.env.SMTP_PORT || "465", 10),
		secure: process.env.SMTP_SECURE === "true", // true for 465, false for 587
		auth: {
			user: process.env.SMTP_USER, // Your sender email (e.g. gmail account)
			pass: process.env.SMTP_PASS, // Your sender email App Password
		},
	});

	const mailOptions = {
		from: `"${formData.name}" <${process.env.SMTP_USER || formData.email}>`,
		to: "sajinsathyan001@gmail.com", // Admin recipient address
		replyTo: formData.email,
		subject: `New Inquiry: ${formData.projectType} from ${formData.name}`,
		text: `
========================================
NEW PORTFOLIO INQUIRY - VINESH STUDIO
========================================

Name: ${formData.name}
Email: ${formData.email}
Phone: ${formData.phone || "Not provided"}
Project Type: ${formData.projectType}

----------------------------------------
Project Brief:
----------------------------------------
${formData.message}

========================================
This email was generated by Vinesh Studio Contact Form.
		`,
		html: `
<div style="background-color: #0e1218; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
	<div style="max-width: 600px; margin: 0 auto; background-color: #181d26; border: 1px solid rgba(242,237,230,0.08); border-radius: 12px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.4);">
		<!-- Header -->
		<div style="background-color: #1e242f; padding: 30px 40px; border-bottom: 1px solid rgba(242,237,230,0.08);">
			<span style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.15em; color: #e05a44; font-weight: bold; display: block; margin-bottom: 6px;">New Inquiry</span>
			<h1 style="font-size: 24px; font-weight: 800; color: #f2ede6; margin: 0; letter-spacing: -0.02em;">Vinesh Studio</h1>
		</div>
		<!-- Content Body -->
		<div style="padding: 40px; color: #f2ede6;">
			<h2 style="font-size: 18px; font-weight: 700; color: #f2ede6; margin-top: 0; margin-bottom: 24px; border-bottom: 1px solid rgba(242,237,230,0.05); padding-bottom: 12px;">Inquiry Details</h2>
			
			<table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
				<tbody>
					<tr>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: rgba(242,237,230,0.5); font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; width: 140px;">Client Name</td>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: #f2ede6; font-size: 15px; font-weight: bold;">${formData.name}</td>
					</tr>
					<tr>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: rgba(242,237,230,0.5); font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Email</td>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: #e05a44; font-size: 15px; font-weight: bold;"><a href="mailto:${formData.email}" style="color: #e05a44; text-decoration: none;">${formData.email}</a></td>
					</tr>
					<tr>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: rgba(242,237,230,0.5); font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Phone</td>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: #f2ede6; font-size: 15px; font-weight: bold;">${formData.phone || '<span style="color: rgba(242,237,230,0.3); font-weight: normal; font-style: italic;">Not provided</span>'}</td>
					</tr>
					<tr>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: rgba(242,237,230,0.5); font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Project Type</td>
						<td style="padding: 12px 0; border-bottom: 1px solid rgba(242,237,230,0.05); color: #f2ede6; font-size: 15px; font-weight: bold;">${formData.projectType}</td>
					</tr>
				</tbody>
			</table>

			<h3 style="font-size: 13px; font-weight: 700; color: rgba(242,237,230,0.5); text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 12px; margin-top: 0;">Project Brief</h3>
			<div style="background-color: #1e242f; border: 1px solid rgba(242,237,230,0.05); border-left: 3px solid #e05a44; padding: 20px; border-radius: 6px; color: #f2ede6; font-size: 15px; line-height: 1.6; white-space: pre-wrap; margin: 0;">${formData.message}</div>
		</div>
		<!-- Footer info -->
		<div style="background-color: #11151d; padding: 20px 40px; text-align: center; border-top: 1px solid rgba(242,237,230,0.05);">
			<p style="margin: 0; font-size: 12px; color: rgba(242,237,230,0.35);">This email was automatically generated by Vinesh Studio Contact Form.</p>
		</div>
	</div>
</div>
		`,
	};

	try {
		await transporter.sendMail(mailOptions);
		return { success: true };
	} catch (error: any) {
		console.error("Email sending failed:", error);
		return {
			success: false,
			error: error.message || "Failed to send email message.",
		};
	}
}
