"use server";

import nodemailer from "nodemailer";

interface ContactData {
	name: string;
	email: string;
	phone: string;
	projectType: string;
	message: string;
}

export async function sendContactEmail(formData: ContactData) {
	// Configure SMTP Transporter
	// These values will be read from environment variables (.env.local)
	const transporter = nodemailer.createTransport({
		host: process.env.SMTP_HOST || "smtp.gmail.com",
		port: parseInt(process.env.SMTP_PORT || "465", 10),
		secure: process.env.SMTP_SECURE === "true", // true for 465, false for 587
		auth: {
			user: process.env.SMTP_USER, // Your sender email (e.g. gmail account)
			pass: process.env.SMTP_PASS, // Your sender email App Password
		},
	});

	const adminMailOptions = {
		from: `"${formData.name} via Vichu Studio" <${process.env.SMTP_USER || "vichuzstudio@gmail.com"}>`,
		to: "vichuzstudio@gmail.com, sajinsathyan001@gmail.com", // Admin recipient addresses
		replyTo: formData.email,
		subject: `New Inquiry: ${formData.projectType} from ${formData.name}`,
		text: `
========================================
NEW PORTFOLIO INQUIRY - Vichu Studio
========================================

Name: ${formData.name}
Email: ${formData.email}
Phone: ${formData.phone || "Not provided"}
Project Type: ${formData.projectType}

----------------------------------------
Project Brief:
----------------------------------------
${formData.message}

========================================
This email was generated by Vichu Studio Contact Form.
		`,
		html: `
<div style="background-color: #f5f5f7; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
	<div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid rgba(29,29,31,0.08); border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.04);">
		<!-- Header -->
		<div style="background-color: #1d1d1f; padding: 28px 36px;">
			<span style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.15em; color: #e05a44; font-weight: bold; display: block; margin-bottom: 6px;">New Inquiry</span>
			<h1 style="font-size: 22px; font-weight: 800; color: #ffffff; margin: 0; letter-spacing: -0.02em;">Vichu Studio</h1>
		</div>
		<!-- Content Body -->
		<div style="padding: 36px; color: #1d1d1f;">
			<h2 style="font-size: 17px; font-weight: 700; color: #1d1d1f; margin-top: 0; margin-bottom: 20px; border-bottom: 1px solid rgba(29,29,31,0.08); padding-bottom: 10px;">Inquiry Details</h2>
			
			<table style="width: 100%; border-collapse: collapse; margin-bottom: 26px;">
				<tbody>
					<tr>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #86868b; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; width: 130px;">Client Name</td>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #1d1d1f; font-size: 15px; font-weight: bold;">${formData.name}</td>
					</tr>
					<tr>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #86868b; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Email</td>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #e05a44; font-size: 15px; font-weight: bold;"><a href="mailto:${formData.email}" style="color: #e05a44; text-decoration: none;">${formData.email}</a></td>
					</tr>
					<tr>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #86868b; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Phone</td>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #1d1d1f; font-size: 15px; font-weight: bold;">${formData.phone || '<span style="color: #86868b; font-weight: normal; font-style: italic;">Not provided</span>'}</td>
					</tr>
					<tr>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #86868b; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;">Project Type</td>
						<td style="padding: 10px 0; border-bottom: 1px solid rgba(29,29,31,0.06); color: #1d1d1f; font-size: 15px; font-weight: bold;">${formData.projectType}</td>
					</tr>
				</tbody>
			</table>

			<h3 style="font-size: 13px; font-weight: 700; color: #86868b; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 10px; margin-top: 0;">Project Brief</h3>
			<div style="background-color: #f5f5f7; border: 1px solid rgba(29,29,31,0.08); border-left: 3px solid #e05a44; padding: 18px; border-radius: 8px; color: #1d1d1f; font-size: 14px; line-height: 1.6; white-space: pre-wrap; margin: 0;">${formData.message}</div>
		</div>
		<!-- Footer info -->
		<div style="background-color: #fbfbfd; padding: 18px 36px; text-align: center; border-top: 1px solid rgba(29,29,31,0.06);">
			<p style="margin: 0; font-size: 12px; color: #86868b;">This email was automatically generated by Vichu Studio Contact Form.</p>
		</div>
	</div>
</div>
		`,
	};

	const userThankYouMailOptions = {
		from: `"Vichu Studio" <${process.env.SMTP_USER || "vichuzstudio@gmail.com"}>`,
		to: formData.email,
		replyTo: "vichuzstudio@gmail.com",
		subject: `Thank you for reaching out, ${formData.name} — Vichu Studio`,
		text: `
Hi ${formData.name},

Thank you for reaching out to Vichu Studio.

I have received your inquiry regarding "${formData.projectType}" and will review the details carefully. I'll get back to you shortly (typically within 24–48 hours).

Here is a copy of what you submitted:
----------------------------------------
Project Type: ${formData.projectType}
Phone: ${formData.phone || "Not provided"}

Message:
${formData.message}
----------------------------------------

If you have any further ideas, decks, or references to share in the meantime, feel free to reply directly to this email.

Best regards,
Vinesh
Creative Director · Vichu Studio
vichuzstudio@gmail.com
		`,
		html: `
<div style="background-color: #f5f5f7; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
	<div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid rgba(29,29,31,0.08); border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.04);">
		<!-- Header -->
		<div style="background-color: #1d1d1f; padding: 28px 36px;">
			<span style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.15em; color: #e05a44; font-weight: bold; display: block; margin-bottom: 6px;">Thank You</span>
			<h1 style="font-size: 22px; font-weight: 800; color: #ffffff; margin: 0; letter-spacing: -0.02em;">Vichu Studio</h1>
		</div>

		<!-- Body -->
		<div style="padding: 36px; color: #1d1d1f; line-height: 1.6;">
			<p style="font-size: 17px; font-weight: 700; color: #1d1d1f; margin-top: 0; margin-bottom: 14px;">
				Hi ${formData.name},
			</p>
			<p style="font-size: 15px; color: #1d1d1f; margin-bottom: 20px;">
				Thank you for reaching out. I've received your note regarding <strong style="color: #e05a44;">${formData.projectType}</strong> and am excited to learn more about what you have in mind.
			</p>
			<p style="font-size: 15px; color: #6e6e73; margin-bottom: 26px;">
				I review every inquiry personally and will get back to you within <strong>24–48 hours</strong> with initial thoughts or next steps.
			</p>

			<!-- Summary Box -->
			<div style="background-color: #f5f5f7; border: 1px solid rgba(29,29,31,0.08); border-radius: 10px; padding: 20px; margin-bottom: 28px;">
				<span style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #86868b; font-weight: 700; display: block; margin-bottom: 12px;">Your Submission Summary</span>
				<p style="font-size: 14px; color: #1d1d1f; margin: 0 0 8px 0;"><strong>Project:</strong> ${formData.projectType}</p>
				<p style="font-size: 14px; color: #1d1d1f; margin: 0 0 12px 0;"><strong>Phone:</strong> ${formData.phone || "Not provided"}</p>
				<div style="font-size: 13px; color: #6e6e73; border-top: 1px solid rgba(29,29,31,0.08); pt-2; padding-top: 10px; white-space: pre-wrap;">${formData.message}</div>
			</div>

			<p style="font-size: 14px; color: #6e6e73; margin-bottom: 24px;">
				Have references, moodboards, or additional materials? You can reply directly to this email at any time.
			</p>

			<div style="border-top: 1px solid rgba(29,29,31,0.08); padding-top: 20px; margin-top: 28px;">
				<p style="font-size: 15px; font-weight: bold; color: #1d1d1f; margin: 0;">Vinesh</p>
				<p style="font-size: 13px; color: #86868b; margin: 2px 0 0 0;">Creative Direction · Brand Systems · Digital Experiences</p>
				<p style="font-size: 13px; color: #e05a44; margin: 6px 0 0 0;"><a href="mailto:vichuzstudio@gmail.com" style="color: #e05a44; text-decoration: none;">vichuzstudio@gmail.com</a></p>
			</div>
		</div>

		<!-- Footer -->
		<div style="background-color: #fbfbfd; padding: 18px 36px; text-align: center; border-top: 1px solid rgba(29,29,31,0.06);">
			<p style="margin: 0; font-size: 12px; color: #86868b;">Vichu Studio — Crafting distinctive brand, digital & creative experiences.</p>
		</div>
	</div>
</div>
		`,
	};

	try {
		// Send notification to admin and thank-you confirmation to client
		await Promise.all([
			transporter.sendMail(adminMailOptions),
			transporter.sendMail(userThankYouMailOptions),
		]);
		return { success: true };
	} catch (error: any) {
		console.error("Email sending failed:", error);
		return {
			success: false,
			error: error.message || "Failed to send email message.",
		};
	}
}
