export interface Project {
	case_slug: string;
	num: string;
	emoji: string;
	title: string;
	subtitle: string;
	desc: string[];
	gallery: string[];
}

export const PROJECTS: Project[] = [
	{
		case_slug: "mashroob",
		num: "Project 1",
		emoji: "⚡",
		title: "Mashroob App",
		subtitle: "Concept - Branding",
		desc: [
			"Led complete creative vision for a luxury sports lounge concept that achieved rapid brand recognition in the UAE market within 3 months. Strategic creative decisions drove significant footfall and hospitality revenue through bold brand positioning and immersive campaign execution.",
		],
		gallery: [
			"/works/mashroob/img1.gif",
			"/works/mashroob/img2.jpg",
			"/works/mashroob/img3.png",
			"/works/mashroob/img4.gif",
			"/works/mashroob/img5.jpg",
			"/works/mashroob/img6.png",
			"/works/mashroob/img7.jpg",
			"/works/mashroob/img8.png",
			"/works/mashroob/img9.jpg",
			"/works/mashroob/img10.png",
			"/works/mashroob/img11.jpg",
			"/works/mashroob/img12.jpg",
			"/works/mashroob/img13.jpg",
			"/works/mashroob/img14.jpg",
			"/works/mashroob/img15.jpg",
		],
	},
	{
		case_slug: "eleven-kicks",
		num: "Project 2",
		emoji: "🌿",
		title: "Eleven11Kicks.com",
		subtitle: "Concept - Branding",
		desc: [
			"Mood Board, Logo Design, Color Schemes, Brand guidelines, Packaging, Photography, Store branding, Website and social media Campaigns",
		],
		gallery: [
			"/works/eleven-kicks/img1.jpg",
			"/works/eleven-kicks/img2.jpg",
			"/works/eleven-kicks/img3.jpg",
			"/works/eleven-kicks/img4.jpg",
			"/works/eleven-kicks/img5.jpg",
			"/works/eleven-kicks/img6.jpg",
			"/works/eleven-kicks/img7.jpg",
			"/works/eleven-kicks/img8.jpg",
			"/works/eleven-kicks/img9.jpg",
			"/works/eleven-kicks/img10.jpg",
			"/works/eleven-kicks/img11.jpg",
			"/works/eleven-kicks/img12.jpg",
			"/works/eleven-kicks/img13.jpg",
			"/works/eleven-kicks/img14.jpg",
			"/works/eleven-kicks/img15.jpg",
		],
	},
	{
		case_slug: "salt-caramel",
		num: "Project 3",
		emoji: "🌿",
		title: "Salt & Caramel",
		subtitle:
			"Mood Board, Logo Design, Color Schemes, Brand guidelines, Packaging, Photography, Menu Design, Store branding, Website and social media Campaigns",
		desc: [
			"Salt and Caramel Cafe was one of our latest addition to the capital motion portfolio. The idea was to create one of its kind coffee shop chain in Abu Dhabi. A relaxed destination cafe where families & friends can enjoy delicious coffee and treats during timeless moments. Overall and all-day coffee and breakfast spot.",
			"We were building a brand here so we need to start everything from scratch. It was planned to have a straight forward simple name-based logo and more appealing bright color schemes to make the brand stand out. ",
		],
		gallery: [
			"/works/salt-caramel/img1.jpg",
			"/works/salt-caramel/img2.jpg",
			"/works/salt-caramel/img3.jpg",
			"/works/salt-caramel/img4.jpg",
			"/works/salt-caramel/img5.jpg",
			"/works/salt-caramel/img6.jpg",
			"/works/salt-caramel/img7.jpg",
			"/works/salt-caramel/img8.jpg",
			"/works/salt-caramel/img9.jpg",
			"/works/salt-caramel/img10.jpg",
			"/works/salt-caramel/img11.jpg",
			"/works/salt-caramel/img12.jpg",
			"/works/salt-caramel/img13.jpg",
			"/works/salt-caramel/img14.jpg",
			"/works/salt-caramel/img15.jpg",
		],
	},
	{
		case_slug: "city-view",
		num: "Project 4",
		emoji: "🌿",
		title: "City View",
		subtitle: "Concept - Branding ",
		desc: [""],
		gallery: [
			"/works/city-view/img1.webp",
			"/works/city-view/img2.webp",
			"/works/city-view/img3.webp",
			"/works/city-view/img4.webp",
			"/works/city-view/img5.webp",
			"/works/city-view/img6.webp",
			"/works/city-view/img7.webp",
			"/works/city-view/img8.webp",
			"/works/city-view/img9.webp",
			"/works/city-view/img10.webp",
			"/works/city-view/img11.webp",
			"/works/city-view/img12.webp",
			"/works/city-view/img13.webp",
			"/works/city-view/img14.webp",
			"/works/city-view/img15.webp",
			"/works/city-view/img16.webp",
			"/works/city-view/img17.webp",
			"/works/city-view/img18.webp",
			"/works/city-view/img19.webp",
			"/works/city-view/img20.webp",
			"/works/city-view/img21.webp",
			"/works/city-view/img22.webp",
			"/works/city-view/img23.webp",
			"/works/city-view/img24.webp",
			"/works/city-view/img25.webp",
			"/works/city-view/img26.webp",
			"/works/city-view/img27.webp",
			"/works/city-view/img28.webp",
			"/works/city-view/img29.webp",
			"/works/city-view/img30.webp",
			"/works/city-view/img31.webp",
			"/works/city-view/img32.webp",
			"/works/city-view/img33.jpg",
		],
	},
	{
		case_slug: "malika-chandan",
		num: "Project 5",
		emoji: "🌿",
		title: "Malika & Chandan",
		subtitle: "Concept - Logo Design & Branding ",
		desc: [""],
		gallery: [
			"/works/malika-chandan/img1.webp",
			"/works/malika-chandan/img2.jpg",
			"/works/malika-chandan/img3.webp",
			"/works/malika-chandan/img4.webp",
			"/works/malika-chandan/img5.webp",
			"/works/malika-chandan/img6.webp",
			"/works/malika-chandan/img7.webp",
			"/works/malika-chandan/img8.webp",
			"/works/malika-chandan/img9.webp",
			"/works/malika-chandan/img10.webp",
		],
	},
	{
		case_slug: "choco-zella",
		num: "Project 6",
		emoji: "🌿",
		title: "ChocoZella",
		subtitle: "Concept - ReBranding Idea ",
		desc: [""],
		gallery: [
			"/works/choco-zella/img1.webp",
			"/works/choco-zella/img2.webp",
			"/works/choco-zella/img3.webp",
			"/works/choco-zella/img4.webp",
			"/works/choco-zella/img5.webp",
			"/works/choco-zella/img6.webp",
			"/works/choco-zella/img7.webp",
			"/works/choco-zella/img8.webp",
			"/works/choco-zella/img9.webp",
			"/works/choco-zella/img10.webp",
		],
	},
	{
		case_slug: "what-we-should-care-about",
		num: "Project 7",
		emoji: "🌿",
		title: "What we should care about",
		subtitle: "Concept - Personal Thoughts ",
		desc: [""],
		gallery: [
			"/works/what-we-should-care-about/img1.jpg",
			"/works/what-we-should-care-about/img2.jpg",
			"/works/what-we-should-care-about/img3.jpg",
			"/works/what-we-should-care-about/img4.jpg",
			"/works/what-we-should-care-about/img5.jpg",
		],
	},
	{
		case_slug: "lover",
		num: "Project 8",
		emoji: "🌿",
		title: "Lover",
		subtitle: "Music Album Cover Design ",
		desc: [""],
		gallery: [
			"/works/lover/img1.jpg",
			"/works/lover/img2.jpg",
			"/works/lover/img3.jpg",
			"/works/lover/img4.jpg",
			"/works/lover/img5.jpg",
			"/works/lover/img6.jpg",
		],
	},
	{
		case_slug: "cafe-des-royal-femmes",
		num: "Project 9",
		emoji: "🌿",
		title: "Cafe Des Royal Femmes",
		subtitle: "Concept - Proposal",
		desc: [
			"Mood Board, Logo Design, Color Schemes, Brand guidelines, Packaging.",
			"Cafe des Royal Femme is a themed concept brand proposal for Capital Motion Portfolio. The concept needs to be developed into a corporate proposal with a matching mood board and a perfect logo and brand identity.",
		],
		gallery: [
			"/works/cafe-des-royal-femmes/img1.gif",
			"/works/cafe-des-royal-femmes/img2.jpg",
			"/works/cafe-des-royal-femmes/img3.jpg",
			"/works/cafe-des-royal-femmes/img4.jpg",
			"/works/cafe-des-royal-femmes/img5.jpg",
			"/works/cafe-des-royal-femmes/img6.jpg",
			"/works/cafe-des-royal-femmes/img7.jpg",
			"/works/cafe-des-royal-femmes/img8.jpg",
			"/works/cafe-des-royal-femmes/img9.jpg",
			"/works/cafe-des-royal-femmes/img10.jpg",
			"/works/cafe-des-royal-femmes/img11.jpg",
			"/works/cafe-des-royal-femmes/img12.jpg",
			"/works/cafe-des-royal-femmes/img13.png",
		],
	},
	{
		case_slug: "tokyo-grill-bar",
		num: "Project 10",
		emoji: "🌿",
		title: "Tokyo Grill & Bar",
		subtitle: "Logo & Rebranding Ideas ",
		desc: [
			"Mood Board, Logo Design, Color Schemes, Brand guidelines, Packaging.",
			"Tokyo Grill and Bar is one of the famous Japanese restaurants in Abu Dhabi operating under the portfolio of Capital Motion. The concept is to rebrand the existing logo and visual identity to a new and modern look. We tried to do a more minimal style theme for branding this elegant restaurant. ",
		],
		gallery: [
			"/works/tokyo-grill-bar/img1.jpg",
			"/works/tokyo-grill-bar/img2.jpg",
			"/works/tokyo-grill-bar/img3.jpg",
			"/works/tokyo-grill-bar/img4.jpg",
			"/works/tokyo-grill-bar/img5.jpg",
			"/works/tokyo-grill-bar/img6.jpg",
			"/works/tokyo-grill-bar/img7.jpg",
			"/works/tokyo-grill-bar/img8.jpg",
			"/works/tokyo-grill-bar/img9.jpg",
			"/works/tokyo-grill-bar/img10.jpg",
			"/works/tokyo-grill-bar/img11.jpg",
		],
	},
	{
		case_slug: "we-r-entertainment",
		num: "Project 11",
		emoji: "🌿",
		title: "We R Entertainment",
		subtitle: "Logo Design - Branding ",
		desc: [
			"Mood Board, Logo Design, Color Schemes, Brand guidelines, Website, and social media",
			"Complete branding and visual identity. The company 'We R Entertainment' is owned by my friends and he needs a bold and black white themed logo and brand identity.",
		],
		gallery: [
			"/works/we-r-entertainment/img1.jpg",
			"/works/we-r-entertainment/img2.jpg",
			"/works/we-r-entertainment/img3.jpg",
			"/works/we-r-entertainment/img4.gif",
			"/works/we-r-entertainment/img5.jpg",
			"/works/we-r-entertainment/img6.jpg",
			"/works/we-r-entertainment/img7.jpg",
			"/works/we-r-entertainment/img8.jpg",
			"/works/we-r-entertainment/img9.jpg",
			"/works/we-r-entertainment/img10.jpg",
			"/works/we-r-entertainment/img11.jpg",
			"/works/we-r-entertainment/img12.png",
			"/works/we-r-entertainment/img13.jpg",
			"/works/we-r-entertainment/img14.gif",
			"/works/we-r-entertainment/img16.png",
			"/works/we-r-entertainment/img15.jpg",
		],
	},
	{
		case_slug: "verdure-world-wide",
		num: "Project 12",
		emoji: "🌿",
		title: "Verdure World Wide",
		subtitle: "Logo Design - Branding",
		desc: [
			"Mood Board, Logo Design, Color Schemes, Brand guidelines",
			"Vedure is an UAE based Logistics company which imports pulses and grains from India and surrounding asian coun tries to UAE. The client wanted a new innovative logo which should have pride and the color should mathc the business model. I chose green and dark blue as the color theme.",
		],
		gallery: [
			"/works/verdure-world-wide/img1.jpg",
			"/works/verdure-world-wide/img2.jpg",
			"/works/verdure-world-wide/img3.jpg",
			"/works/verdure-world-wide/img4.jpg",
			"/works/verdure-world-wide/img5.jpg",
			"/works/verdure-world-wide/img6.jpg",
			"/works/verdure-world-wide/img7.jpg",
			"/works/verdure-world-wide/img8.jpg",
			"/works/verdure-world-wide/img9.jpg",
			"/works/verdure-world-wide/img10.jpg",
			"/works/verdure-world-wide/img11.jpg",
			"/works/verdure-world-wide/img12.jpg",
			"/works/verdure-world-wide/img13.gif",
			"/works/verdure-world-wide/img14.gif",
		],
	},
	{
		case_slug: "red-crew-international",
		num: "Project 13",
		emoji: "🌿",
		title: "Red Crew International",
		subtitle: "Logo Design - Branding ",
		desc: [
			"Logo Design, Color Schemes, Brand guidelines",
			"Red Crew is one of the companies I spend my career in India. Red crew an event management company that operates in Chennai and South India.",
			"They do events, shows, product activations, promotions etc. They required a new logo, simple and bold, straight on the point. so here we go.",
		],
		gallery: [
			"/works/red-crew-international/img1.jpg",
			"/works/red-crew-international/img2.jpg",
			"/works/red-crew-international/img3.jpg",
			"/works/red-crew-international/img4.jpg",
			"/works/red-crew-international/img5.gif",
			"/works/red-crew-international/img6.gif",
			"/works/red-crew-international/img7.jpg",
			"/works/red-crew-international/img8.jpg",
			"/works/red-crew-international/img9.jpg",
			"/works/red-crew-international/img10.gif",
			"/works/red-crew-international/img11.jpg",
		],
	},
	{
		case_slug: "aquarium",
		num: "Project 14",
		emoji: "🌿",
		title: "Aquarium",
		subtitle: "Logo Design - Rebranding",
		desc: [
			"Logo Design, Color Schemes, Brand guidelines, Brand Identity",
			"Aquarium Seafood restaurant, Abudhabi. Redesign the existing logo as it is outdated to a modern look without losing its original shape. Give a new brand identity using modern and relevant color schemes and designs suiting the business model.",
		],
		gallery: [
			"/works/aquarium/img1.gif",
			"/works/aquarium/img2.jpg",
			"/works/aquarium/img3.jpg",
			"/works/aquarium/img4.jpg",
			"/works/aquarium/img5.jpg",
			"/works/aquarium/img6.jpg",
			"/works/aquarium/img7.jpg",
			"/works/aquarium/img8.jpg",
			"/works/aquarium/img9.jpg",
			"/works/aquarium/img10.jpg",
			"/works/aquarium/img11.jpg",
		],
	},
];
